import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import Background from "@/components/home/Background";

const ibm_plex_sans_thai = IBM_Plex_Sans_Thai({
  weight: "400",
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${ibm_plex_sans_thai.className} antialiased`}>
          <Provider>
            <Background />
            <Navbar />
            <main className="container">{children}</main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
